version: '2.2'
services:
   db:
      image: 'postgres:12.1'
      ports:
         - '5432:5432'
      environment:
         POSTGRES_DB: hpgMethyl
      volumes:
       - postgres:/data/postgres
      networks:
         webapp:
            ipv4_address: 172.19.0.3
   tomcat:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
        - '8080:8080'
      networks:
         webapp:
            ipv4_address: 172.19.0.2
        
volumes:
   postgres:

networks:
  webapp:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
            